[package]
name = "cube-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }

# add main as binary
[[bin]]
name = "cube-solver"
path = "src/main.rs"
